/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Voice
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.kandy.rest.voice.v1.dialingpermissions.country;

import com.kandy.base.Reader;
import com.kandy.base.ResourceSet;
import com.kandy.exception.ApiConnectionException;
import com.kandy.exception.ApiException;
import com.kandy.exception.RestException;
import com.kandy.http.HttpMethod;
import com.kandy.http.Request;
import com.kandy.http.Response;
import com.kandy.http.KandyRestClient;
import com.twilio.rest.Domains;
import com.kandy.base.Page;

public class HighriskSpecialPrefixReader extends Reader<HighriskSpecialPrefix> {
    private String pathIsoCode;
    private Integer pageSize;

    public HighriskSpecialPrefixReader(final String pathIsoCode) {
        this.pathIsoCode = pathIsoCode;
    }

    public HighriskSpecialPrefixReader setPageSize(final Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    @Override
    public ResourceSet<HighriskSpecialPrefix> read(final KandyRestClient client) {
        return new ResourceSet<>(this, client, firstPage(client));
    }

    public Page<HighriskSpecialPrefix> firstPage(final KandyRestClient client) {
        String path = "/v1/DialingPermissions/Countries/{IsoCode}/HighRiskSpecialPrefixes";
        path = path.replace("{" + "IsoCode" + "}", this.pathIsoCode.toString());

        Request request = new Request(
                HttpMethod.GET,
                Domains.VOICE.toString(),
                path);

        addQueryParams(request);
        return pageForRequest(client, request);
    }

    private Page<HighriskSpecialPrefix> pageForRequest(final KandyRestClient client, final Request request) {
        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("HighriskSpecialPrefix read failed: Unable to connect to server");
        } else if (!KandyRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return Page.fromJson(
                "content",
                response.getContent(),
                HighriskSpecialPrefix.class,
                client.getObjectMapper());
    }

    @Override
    public Page<HighriskSpecialPrefix> previousPage(final Page<HighriskSpecialPrefix> page,
            final KandyRestClient client) {
        Request request = new Request(
                HttpMethod.GET,
                page.getPreviousPageUrl(Domains.VOICE.toString()));
        return pageForRequest(client, request);
    }

    @Override
    public Page<HighriskSpecialPrefix> nextPage(final Page<HighriskSpecialPrefix> page, final KandyRestClient client) {
        Request request = new Request(
                HttpMethod.GET,
                page.getNextPageUrl(Domains.VOICE.toString()));
        return pageForRequest(client, request);
    }

    @Override
    public Page<HighriskSpecialPrefix> getPage(final String targetUrl, final KandyRestClient client) {
        Request request = new Request(
                HttpMethod.GET,
                targetUrl);

        return pageForRequest(client, request);
    }

    private void addQueryParams(final Request request) {
        if (pageSize != null) {

            request.addQueryParam("PageSize", pageSize.toString());
        }

        if (getPageSize() != null) {
            request.addQueryParam("PageSize", Integer.toString(getPageSize()));
        }
    }
}
