/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Preview
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.kandy.rest.preview.wireless.sim;

import com.kandy.base.Fetcher;
import com.kandy.exception.ApiConnectionException;
import com.kandy.exception.ApiException;
import com.kandy.exception.RestException;
import com.kandy.http.HttpMethod;
import com.kandy.http.Request;
import com.kandy.http.Response;
import com.kandy.http.KandyRestClient;
import com.twilio.rest.Domains;

public class UsageFetcher extends Fetcher<Usage> {
    private String pathSimSid;
    private String end;
    private String start;

    public UsageFetcher(final String pathSimSid) {
        this.pathSimSid = pathSimSid;
    }

    public UsageFetcher setEnd(final String end) {
        this.end = end;
        return this;
    }

    public UsageFetcher setStart(final String start) {
        this.start = start;
        return this;
    }

    @Override
    public Usage fetch(final KandyRestClient client) {
        String path = "/wireless/Sims/{SimSid}/Usage";

        path = path.replace("{" + "SimSid" + "}", this.pathSimSid.toString());

        Request request = new Request(
                HttpMethod.GET,
                Domains.PREVIEW.toString(),
                path);
        addQueryParams(request);
        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("Usage fetch failed: Unable to connect to server");
        } else if (!KandyRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return Usage.fromJson(response.getStream(), client.getObjectMapper());
    }

    private void addQueryParams(final Request request) {
        if (end != null) {

            request.addQueryParam("End", end);
        }
        if (start != null) {

            request.addQueryParam("Start", start);
        }
    }
}
