/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Taskrouter
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.kandy.rest.taskrouter.v1.workspace;

import com.kandy.base.Reader;
import com.kandy.base.ResourceSet;
import com.kandy.exception.ApiConnectionException;
import com.kandy.exception.ApiException;
import com.kandy.exception.RestException;
import com.kandy.http.HttpMethod;
import com.kandy.http.Request;
import com.kandy.http.Response;
import com.kandy.http.KandyRestClient;
import com.twilio.rest.Domains;
import com.kandy.base.Page;

public class WorkerReader extends Reader<Worker> {
    private String pathWorkspaceSid;
    private String activityName;
    private String activitySid;
    private String available;
    private String friendlyName;
    private String targetWorkersExpression;
    private String taskQueueName;
    private String taskQueueSid;
    private String ordering;
    private Integer pageSize;

    public WorkerReader(final String pathWorkspaceSid) {
        this.pathWorkspaceSid = pathWorkspaceSid;
    }

    public WorkerReader setActivityName(final String activityName) {
        this.activityName = activityName;
        return this;
    }

    public WorkerReader setActivitySid(final String activitySid) {
        this.activitySid = activitySid;
        return this;
    }

    public WorkerReader setAvailable(final String available) {
        this.available = available;
        return this;
    }

    public WorkerReader setFriendlyName(final String friendlyName) {
        this.friendlyName = friendlyName;
        return this;
    }

    public WorkerReader setTargetWorkersExpression(final String targetWorkersExpression) {
        this.targetWorkersExpression = targetWorkersExpression;
        return this;
    }

    public WorkerReader setTaskQueueName(final String taskQueueName) {
        this.taskQueueName = taskQueueName;
        return this;
    }

    public WorkerReader setTaskQueueSid(final String taskQueueSid) {
        this.taskQueueSid = taskQueueSid;
        return this;
    }

    public WorkerReader setOrdering(final String ordering) {
        this.ordering = ordering;
        return this;
    }

    public WorkerReader setPageSize(final Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    @Override
    public ResourceSet<Worker> read(final KandyRestClient client) {
        return new ResourceSet<>(this, client, firstPage(client));
    }

    public Page<Worker> firstPage(final KandyRestClient client) {
        String path = "/v1/Workspaces/{WorkspaceSid}/Workers";
        path = path.replace("{" + "WorkspaceSid" + "}", this.pathWorkspaceSid.toString());

        Request request = new Request(
                HttpMethod.GET,
                Domains.TASKROUTER.toString(),
                path);

        addQueryParams(request);
        return pageForRequest(client, request);
    }

    private Page<Worker> pageForRequest(final KandyRestClient client, final Request request) {
        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("Worker read failed: Unable to connect to server");
        } else if (!KandyRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return Page.fromJson(
                "workers",
                response.getContent(),
                Worker.class,
                client.getObjectMapper());
    }

    @Override
    public Page<Worker> previousPage(final Page<Worker> page, final KandyRestClient client) {
        Request request = new Request(
                HttpMethod.GET,
                page.getPreviousPageUrl(Domains.TASKROUTER.toString()));
        return pageForRequest(client, request);
    }

    @Override
    public Page<Worker> nextPage(final Page<Worker> page, final KandyRestClient client) {
        Request request = new Request(
                HttpMethod.GET,
                page.getNextPageUrl(Domains.TASKROUTER.toString()));
        return pageForRequest(client, request);
    }

    @Override
    public Page<Worker> getPage(final String targetUrl, final KandyRestClient client) {
        Request request = new Request(
                HttpMethod.GET,
                targetUrl);

        return pageForRequest(client, request);
    }

    private void addQueryParams(final Request request) {
        if (activityName != null) {

            request.addQueryParam("ActivityName", activityName);
        }
        if (activitySid != null) {

            request.addQueryParam("ActivitySid", activitySid);
        }
        if (available != null) {

            request.addQueryParam("Available", available);
        }
        if (friendlyName != null) {

            request.addQueryParam("FriendlyName", friendlyName);
        }
        if (targetWorkersExpression != null) {

            request.addQueryParam("TargetWorkersExpression", targetWorkersExpression);
        }
        if (taskQueueName != null) {

            request.addQueryParam("TaskQueueName", taskQueueName);
        }
        if (taskQueueSid != null) {

            request.addQueryParam("TaskQueueSid", taskQueueSid);
        }
        if (ordering != null) {

            request.addQueryParam("Ordering", ordering);
        }
        if (pageSize != null) {

            request.addQueryParam("PageSize", pageSize.toString());
        }

        if (getPageSize() != null) {
            request.addQueryParam("PageSize", Integer.toString(getPageSize()));
        }
    }
}
