/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Intelligence
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.kandy.rest.intelligence.v2.transcript;

import com.kandy.base.Fetcher;
import com.kandy.exception.ApiConnectionException;
import com.kandy.exception.ApiException;
import com.kandy.exception.RestException;
import com.kandy.http.HttpMethod;
import com.kandy.http.Request;
import com.kandy.http.Response;
import com.kandy.http.KandyRestClient;
import com.kandy.rest.Domains;

public class OperatorResultFetcher extends Fetcher<OperatorResult> {
    private String pathTranscriptSid;
    private String pathOperatorSid;
    private Boolean redacted;

    public OperatorResultFetcher(final String pathTranscriptSid, final String pathOperatorSid) {
        this.pathTranscriptSid = pathTranscriptSid;
        this.pathOperatorSid = pathOperatorSid;
    }

    public OperatorResultFetcher setRedacted(final Boolean redacted) {
        this.redacted = redacted;
        return this;
    }

    @Override
    public OperatorResult fetch(final KandyRestClient client) {
        String path = "/v2/Transcripts/{TranscriptSid}/OperatorResults/{OperatorSid}";

        path = path.replace("{" + "TranscriptSid" + "}", this.pathTranscriptSid.toString());
        path = path.replace("{" + "OperatorSid" + "}", this.pathOperatorSid.toString());

        Request request = new Request(
                HttpMethod.GET,
                Domains.INTELLIGENCE.toString(),
                path);
        addQueryParams(request);
        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("OperatorResult fetch failed: Unable to connect to server");
        } else if (!KandyRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return OperatorResult.fromJson(response.getStream(), client.getObjectMapper());
    }

    private void addQueryParams(final Request request) {
        if (redacted != null) {

            request.addQueryParam("Redacted", redacted.toString());
        }
    }
}
