/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Microvisor
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.kandy.rest.microvisor.v1.device;

import com.kandy.base.Updater;
import com.kandy.exception.ApiConnectionException;
import com.kandy.exception.ApiException;
import com.kandy.exception.RestException;
import com.kandy.http.HttpMethod;
import com.kandy.http.Request;
import com.kandy.http.Response;
import com.kandy.http.KandyRestClient;
import com.kandy.rest.Domains;

public class DeviceSecretUpdater extends Updater<DeviceSecret> {
    private String pathDeviceSid;
    private String pathKey;
    private String value;

    public DeviceSecretUpdater(final String pathDeviceSid, final String pathKey, final String value) {
        this.pathDeviceSid = pathDeviceSid;
        this.pathKey = pathKey;
        this.value = value;
    }

    public DeviceSecretUpdater setValue(final String value) {
        this.value = value;
        return this;
    }

    @Override
    public DeviceSecret update(final KandyRestClient client) {
        String path = "/v1/Devices/{DeviceSid}/Secrets/{Key}";

        path = path.replace("{" + "DeviceSid" + "}", this.pathDeviceSid.toString());
        path = path.replace("{" + "Key" + "}", this.pathKey.toString());
        path = path.replace("{" + "Value" + "}", this.value.toString());

        Request request = new Request(
                HttpMethod.POST,
                Domains.MICROVISOR.toString(),
                path);
        addPostParams(request);
        Response response = client.request(request);
        if (response == null) {
            throw new ApiConnectionException("DeviceSecret update failed: Unable to connect to server");
        } else if (!KandyRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return DeviceSecret.fromJson(response.getStream(), client.getObjectMapper());
    }

    private void addPostParams(final Request request) {
        if (value != null) {
            request.addPostParam("Value", value);

        }
    }
}
