/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Events
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.kandy.rest.events.v1.subscription;

import com.kandy.base.Updater;
import com.kandy.exception.ApiConnectionException;
import com.kandy.exception.ApiException;
import com.kandy.exception.RestException;
import com.kandy.http.HttpMethod;
import com.kandy.http.Request;
import com.kandy.http.Response;
import com.kandy.http.TwilioRestClient;
import com.kandy.rest.Domains;

public class SubscribedEventUpdater extends Updater<SubscribedEvent> {
    private String pathSubscriptionSid;
    private String pathType;
    private Integer schemaVersion;

    public SubscribedEventUpdater(final String pathSubscriptionSid, final String pathType) {
        this.pathSubscriptionSid = pathSubscriptionSid;
        this.pathType = pathType;
    }

    public SubscribedEventUpdater setSchemaVersion(final Integer schemaVersion) {
        this.schemaVersion = schemaVersion;
        return this;
    }

    @Override
    public SubscribedEvent update(final TwilioRestClient client) {
        String path = "/v1/Subscriptions/{SubscriptionSid}/SubscribedEvents/{Type}";

        path = path.replace("{" + "SubscriptionSid" + "}", this.pathSubscriptionSid.toString());
        path = path.replace("{" + "Type" + "}", this.pathType.toString());

        Request request = new Request(
                HttpMethod.POST,
                Domains.EVENTS.toString(),
                path);
        addPostParams(request);
        Response response = client.request(request);
        if (response == null) {
            throw new ApiConnectionException("SubscribedEvent update failed: Unable to connect to server");
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return SubscribedEvent.fromJson(response.getStream(), client.getObjectMapper());
    }

    private void addPostParams(final Request request) {
        if (schemaVersion != null) {
            request.addPostParam("SchemaVersion", schemaVersion.toString());

        }
    }
}
