name: Test and Deploy
on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: [main]
  schedule:
    # Run automatically at 8AM PST Monday-Friday
    - cron: "0 15 * * 1-5"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        java: [8, 11, 17]
    steps:
      - name: Checkout kandy-java
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "maven"

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - run: mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
      - name: Run Unit Tests
        run: mvn test -B

      - name: Run Cluster Test
        if: (!github.event.pull_request.head.repo.fork)
        env:
          KANDY_ACCOUNT_SID: ${{ secrets.KANDY_ACCOUNT_SID }}
          KANDY_API_KEY: ${{ secrets.KANDY_CLUSTER_TEST_API_KEY}}
          KANDY_API_SECRET: ${{ secrets.KANDY_CLUSTER_TEST_API_KEY_SECRET }}
          KANDY_FROM_NUMBER: ${{ secrets.KANDY_FROM_NUMBER }}
          KANDY_TO_NUMBER: ${{ secrets.KANDY_TO_NUMBER }}
        run: mvn test -DTest="ClusterTest" -B

      - name: SonarCloud Scan
        if: ${{ (github.event_name == 'pull_request' || github.ref_type == 'branch') && matrix.java == 11 && !github.event.pull_request.head.repo.fork }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kandy_kandy-java
